// Categories Data
const categoriesData = {
  Currencies: [
    {
      Currency: "US Dollar",
      Symbol: "$",
      "Currency Code": "USD",
    },
    {
      Currency: "Euro",
      Symbol: "€",
      "Currency Code": "EUR",
    },
    {
      Currency: "British Pound",
      Symbol: "£",
      "Currency Code": "GBP",
    },
    {
      Currency: "Japanese Yen",
      Symbol: "¥",
      "Currency Code": "JPY",
    },
    {
      Currency: "Indian Rupee",
      Symbol: "₹",
      "Currency Code": "INR",
    },
  ],
  Income: [
    "paycheck",
    "bonus",
    "freelance",
    "gifts",
    "gift",
    "rental income",
    "rent income",
    "rent income 2",
    "interest",
    "dividends",
    "side hustle",
    "consulting",
    "cashback",
    "scholarship",
    "child support",
    "lottery",
    "crypto cashout",
    "refund",
    "reimbursement",
    "coaching",
    "stock sale",
    "royalties",
    "pension",
  ],
  Expenses: [
    "rent",
    "groceries",
    "utilities",
    "transportation",
    "transport",
    "insurance",
    "medical",
    "healthcare",
    "internet",
    "subscriptions",
    "entertainment",
    "education",
    "childcare",
    "clothing",
    "travel",
    "vacation",
    "dining out",
    "dining",
    "charity",
    "gym",
    "fuel",
    "maintenance",
  ],
  Accounts: [
    "checking",
    "savings",
    "credit card 1",
    "credit card 2",
    "retirement account",
    "brokerage account",
    "emergency fund",
    "business account",
  ],
  "Debt Pay-Off": [
    "credit card 1",
    "credit card 2",
    "personal loan 1",
    "personal loan 2",
    "mortgage",
    "student loan",
    "auto loan",
    "medical debt",
  ],
  Investments: [
    "stock",
    "bond",
    "mutual fund",
    "ETF",
    "real estate",
    "crypto",
    "index fund",
    "commodities",
  ],
  Frequencies: [
    "daily",
    "weekly",
    "bi-weekly",
    "monthly",
    "quarterly",
    "yearly / one-time",
  ],
};

// Make sure it's available globally
window.categoriesData = categoriesData;
