// Planner Data
const plannerData = {
  "Start Date": "15-Jan-2025",
  "Currency": "$",
  "Current Holding": [
    {
      Account: "checking",
      Amount: 1200.5,
    },
    {
      Account: "savings",
      Amount: 5200.0,
    },
    {
      Account: "emergency fund",
      Amount: 250.75,
    },
    {
      Account: "brokerage account",
      Amount: 3100.0,
    },
  ],

  "Current Outstanding": [
    {
      Account: "credit card 1",
      Amount: 850.0,
    },
    {
      Account: "auto loan",
      Amount: 7200.0,
    },
    {
      Account: "mortgage",
      Amount: 95000.0,
    },
  ],
  "Expected Income": [
    {
      "Sub Category": "paycheck",
      Frequency: "monthly",
      Amount: 5000.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Monthly paycheck",
    },
    {
      "Sub Category": "bonus",
      Frequency: "yearly / one-time",
      Amount: 3000.0,
      "Start Date": "01-Dec-2025",
      "End Date": "31-Dec-2025",
      Notes: "Annual performance bonus",
    },
    {
      "Sub Category": "freelance",
      Frequency: "weekly",
      Amount: 400.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Side freelance project",
    },
    {
      "Sub Category": "dividends",
      Frequency: "quarterly",
      Amount: 250.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Stock dividends",
    },
    {
      "Sub Category": "interest",
      Frequency: "monthly",
      Amount: 50.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Savings account interest",
    },
    {
      "Sub Category": "consulting",
      Frequency: "bi-weekly",
      Amount: 800.0,
      "Start Date": "01-Feb-2025",
      "End Date": "14-Jan-2026",
      Notes: "Consulting gig",
    },
    {
      "Sub Category": "cashback",
      Frequency: "monthly",
      Amount: 100.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Credit card cashback",
    },
    {
      "Sub Category": "rent income",
      Frequency: "monthly",
      Amount: 1200.0,
      "Start Date": "01-Mar-2025",
      "End Date": "14-Jan-2026",
      Notes: "Apartment rent",
    },
    {
      "Sub Category": "scholarship",
      Frequency: "yearly / one-time",
      Amount: 2000.0,
      "Start Date": "01-Sep-2025",
      "End Date": "31-Dec-2025",
      Notes: "Education grant",
    },
    {
      "Sub Category": "royalties",
      Frequency: "quarterly",
      Amount: 500.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Book royalties",
    },
    {
      "Sub Category": "child support",
      Frequency: "monthly",
      Amount: 600.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Court ordered payment",
    },
    {
      "Sub Category": "lottery",
      Frequency: "yearly / one-time",
      Amount: 1000.0,
      "Start Date": "15-Jul-2025",
      "End Date": "15-Jul-2025",
      Notes: "Small prize",
    },
    {
      "Sub Category": "gift",
      Frequency: "yearly / one-time",
      Amount: 300.0,
      "Start Date": "25-Dec-2025",
      "End Date": "25-Dec-2025",
      Notes: "Holiday gift",
    },
    {
      "Sub Category": "crypto cashout",
      Frequency: "yearly / one-time",
      Amount: 2000.0,
      "Start Date": "10-May-2025",
      "End Date": "10-May-2025",
      Notes: "Sold crypto assets",
    },
    {
      "Sub Category": "refund",
      Frequency: "yearly / one-time",
      Amount: 150.0,
      "Start Date": "01-Apr-2025",
      "End Date": "01-Apr-2025",
      Notes: "Tax refund",
    },
    {
      "Sub Category": "reimbursement",
      Frequency: "yearly / one-time",
      Amount: 500.0,
      "Start Date": "10-Mar-2025",
      "End Date": "10-Mar-2025",
      Notes: "Business expense reimbursement",
    },
    {
      "Sub Category": "coaching",
      Frequency: "weekly",
      Amount: 200.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Tutoring classes",
    },
    {
      "Sub Category": "rent income 2",
      Frequency: "monthly",
      Amount: 900.0,
      "Start Date": "01-Feb-2025",
      "End Date": "14-Jan-2026",
      Notes: "Garage rental",
    },
    {
      "Sub Category": "stock sale",
      Frequency: "yearly / one-time",
      Amount: 3500.0,
      "Start Date": "15-Jun-2025",
      "End Date": "15-Jun-2025",
      Notes: "Sold some stocks",
    },
    {
      "Sub Category": "pension",
      Frequency: "monthly",
      Amount: 1500.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Retirement pension",
    },
  ],
  "Planned Expenses": [
    {
      "Sub-Category": "rent",
      Frequency: "monthly",
      Amount: 1000.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Monthly rent",
    },
    {
      "Sub-Category": "utilities",
      Frequency: "monthly",
      Amount: 200.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Electricity and water",
    },
    {
      "Sub-Category": "internet",
      Frequency: "monthly",
      Amount: 50.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Broadband connection",
    },
    {
      "Sub-Category": "groceries",
      Frequency: "weekly",
      Amount: 150.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Household groceries",
    },
    {
      "Sub-Category": "transport",
      Frequency: "monthly",
      Amount: 100.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Public transport pass",
    },
    {
      "Sub-Category": "insurance",
      Frequency: "yearly / one-time",
      Amount: 1200.0,
      "Start Date": "01-Apr-2025",
      "End Date": "14-Jan-2026",
      Notes: "Car insurance",
    },
    {
      "Sub-Category": "subscriptions",
      Frequency: "monthly",
      Amount: 60.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Streaming services",
    },
    {
      "Sub-Category": "healthcare",
      Frequency: "quarterly",
      Amount: 300.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Medical checkups",
    },
    {
      "Sub-Category": "dining",
      Frequency: "weekly",
      Amount: 100.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Eating out",
    },
    {
      "Sub-Category": "entertainment",
      Frequency: "monthly",
      Amount: 120.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Movies, events",
    },
    {
      "Sub-Category": "gym",
      Frequency: "monthly",
      Amount: 45.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Fitness membership",
    },
    {
      "Sub-Category": "vacation",
      Frequency: "yearly / one-time",
      Amount: 2000.0,
      "Start Date": "01-Jun-2025",
      "End Date": "30-Jun-2025",
      Notes: "Summer trip",
    },
    {
      "Sub-Category": "education",
      Frequency: "quarterly",
      Amount: 800.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Course fees",
    },
    {
      "Sub-Category": "gifts",
      Frequency: "yearly / one-time",
      Amount: 300.0,
      "Start Date": "25-Dec-2025",
      "End Date": "25-Dec-2025",
      Notes: "Holiday gifts",
    },
    {
      "Sub-Category": "clothing",
      Frequency: "quarterly",
      Amount: 400.0,
      "Start Date": "01-Feb-2025",
      "End Date": "14-Jan-2026",
      Notes: "Seasonal shopping",
    },
    {
      "Sub-Category": "fuel",
      Frequency: "monthly",
      Amount: 150.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Car fuel",
    },
    {
      "Sub-Category": "maintenance",
      Frequency: "quarterly",
      Amount: 250.0,
      "Start Date": "01-Mar-2025",
      "End Date": "14-Jan-2026",
      Notes: "House maintenance",
    },
    {
      "Sub-Category": "loan EMI",
      Frequency: "monthly",
      Amount: 600.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Personal loan repayment",
    },
  ],
  "Planned Investments": [
    {
      "Sub-Category": "stock",
      Frequency: "monthly",
      Amount: 500.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Regular stock investments",
    },
    {
      "Sub-Category": "ETF",
      Frequency: "bi-weekly",
      Amount: 300.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "S&P 500 ETF contributions",
    },
    {
      "Sub-Category": "mutual fund",
      Frequency: "monthly",
      Amount: 400.0,
      "Start Date": "01-Feb-2025",
      "End Date": "14-Jan-2026",
      Notes: "Diversified mutual fund",
    },
    {
      "Sub-Category": "bond",
      Frequency: "quarterly",
      Amount: 1000.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Government bonds",
    },
    {
      "Sub-Category": "crypto",
      Frequency: "weekly",
      Amount: 100.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "Bitcoin and Ethereum",
    },
    {
      "Sub-Category": "real estate",
      Frequency: "yearly / one-time",
      Amount: 5000.0,
      "Start Date": "01-Jun-2025",
      "End Date": "30-Jun-2025",
      Notes: "REIT investment",
    },
    {
      "Sub-Category": "commodities",
      Frequency: "quarterly",
      Amount: 250.0,
      "Start Date": "01-Mar-2025",
      "End Date": "14-Jan-2026",
      Notes: "Gold and silver",
    },
    {
      "Sub-Category": "savings",
      Frequency: "monthly",
      Amount: 800.0,
      "Start Date": "15-Jan-2025",
      "End Date": "14-Jan-2026",
      Notes: "High-yield savings account",
    },
  ],
};

// Make sure it's available globally
window.plannerData = plannerData;
